### ISSUE TITLE
Add more Array methods

### ISSUE THREAD

**Issue by project-eutopia** [project-eutopia/keisan#27]
Currently can only get values inside of arrays or get the size of an array.  Could add support for splices, or even functional math operations on arrays.

**Comment by project-eutopia** [comment]
Issue obsolete. We have many array methods now.

**Comment by StefanoMartin** [comment]
I would like to reopen this issue to ask if some other methods for Array can be implemented.
In particular I am interested on the ones that make Array working as a set.

[1,2,3] - [2,3,4] return [1] (difference)
[1,2,3] & [2,3,4] return [2,3] (intersection)
[1,2,3] | [2,3,4] return [1,2,3,4] (union)

Keisan is really a very good library!
