### ISSUE TITLE
Tokenizer issue: grouping symbols in strings

### ISSUE THREAD

**Issue by paulholden2** [project-eutopia/keisan#94]
Gem version: 0.8.0

Hello, I came across an issue involving grouping symbols in string literals throwing off the tokenizer. It looks like the grouping regex is not ignoring grouping symbols inside of string literals. This isn't a problem if the string literal itself uses matched groups (see second example below), but if you put an unpaired grouping symbol anywhere in the string it causes issues.

Running the following in an interactive console demonstrates the issue:

```rb
Keisan::Calculator.new.ast("f('a')")
# => #<Keisan::AST::Function ...>

Keisan::Calculator.new.ast("f('a()')")
# => #<Keisan::AST::Function ...>

Keisan::Calculator.new.ast("f('a]')")
# raises Keisan::Exceptions::TokenizingError (Unexpected token: "(")

# Another error example
Keisan::Calculator.new.ast("f('a)')")
# raises Keisan::Exceptions::TokenizingError (Unexpected token: "'")
```

**Comment by project-eutopia** [comment]
Thanks for the helpful and clear feedback!  This indeed is an issue with how tokenization works.

My first implementation of "groups" (sets of characters delimited by matching braces) was using a complex recursively defined regular expression.  However characters inside strings should not count against matching braces, so this will need to be updated.

I'll report back here when I have a pull request which fixes this issue and make a new gem version.

**Comment by paulholden2** [comment]
Great to hear! If it's any help, I'm playing around with things on my fork, but am still having issues when using mixed-quotes in a group, e.g.

```rb
Keisan::Calculator.new.ast("f(\"a\", 'b)')")
# Still uses right parens in second string to close group; raises unexpected token '

**Comment by project-eutopia** [comment]
I opened PR #95 which is a (not cleanly refactored) fix to the problem.  I'll take a stab at refactoring it later.  Did you want a new gem version to be pushed in the meantime with this quick fix?

**Comment by paulholden2** [comment]
Awesome! I'm not using Keisan in production yet so no rush, but if you're fine with pushing a new gem version then cleaning things up after, go for it!

**Comment by project-eutopia** [comment]
Sorry, I spent some time refactoring the logic a bit.  It is not the most efficient solution, but it works.

Push new version 0.8.1 just now.  Let me know if this addresses this issue and I will close it.

**Comment by paulholden2** [comment]
All my tests are passing with 0.8.1. Great work!

**Comment by project-eutopia** [comment]
Great to hear, thanks for your contribution.
